function(_bottle_expand_dep _bottle_expanded_dep_ _bottle_dep_)
  if(_bottle_dep_ MATCHES "^@(.+)")
    string(REGEX REPLACE "^@(.+)" "${PROJECT_NAME}+deps+\\1" _bottle_dep_ ${_bottle_dep_})
  elseif(_bottle_dep_ MATCHES "^///(.+)")
    string(REGEX REPLACE "^///(.+)" "\\1" _bottle_dep_ ${_bottle_dep_})
  elseif(_bottle_dep_ MATCHES "^//(.+)")
    string(REGEX REPLACE "^//(.+)" "${PROJECT_NAME}+\\1" _bottle_dep_ ${_bottle_dep_})
  elseif(_bottle_dep_ MATCHES "^(:|/)(.+)")
    string(PREPEND _bottle_dep_ "${BOTTLE_PACKAGE_NAME}")
  endif()
  string(REGEX REPLACE "([^:]+):([^:]+)" "\\1+\\2" _bottle_dep_ ${_bottle_dep_})
  string(REGEX REPLACE "([^:]+):([^:]+)" "\\1+\\2" _bottle_dep_ ${_bottle_dep_})
  string(REPLACE "/" "." _bottle_dep_ ${_bottle_dep_})
  set(${_bottle_expanded_dep_} ${_bottle_dep_} PARENT_SCOPE)
endfunction(_bottle_expand_dep)
